version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/python:3.6.6-stretch-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            make install_dep
      - run:
          name: Run tests
          command: |
            make run_tests

      - deploy:
          name: Start train on the pralform
          command: |
            make run_platform
